# Generated by Django 4.2.2 on 2023-11-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('descricao', models.CharField(max_length=250)),
                ('arquivo', models.FileField(upload_to='files/')),
                ('capa', models.ImageField(upload_to='imagens/news/')),
            ],
        ),
    ]
