# Generated by Django 5.0.2 on 2024-02-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_noticia_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(),
        ),
    ]
