# Generated by Django 5.0.4 on 2024-06-24 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_noticia_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data_atualizacao',
            field=models.DateField(default=datetime.date(2024, 6, 24)),
        ),
    ]
